[package]
name = "github-contrib-stats"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "github-contrib-stats"
path = "src/bin/cli.rs"

[dependencies]
anyhow = "1.0.71"
clap = {version = "4.2.7", features = ["env"]}
git-testament = "0.2.4"
octocrab = "0.21.0"
once_cell = "1.17.1"
prettytable = "0.10.0"
tokio = {version = "1.28.1", features = ["full"]}
