name = "github-contrib-stats"
compatibility_date = "2023-05-17"

main = "cloudflare/build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "cargo install -q worker-build && worker-build --release"
cwd = "cloudflare"
